version: "3.7"

networks:
  backend:

volumes:
  postgres-data:

services:
  proxy:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/nginx-site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend

  postgres:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: laravel_db
      PGDATA: /var/lib/postgresql/data
    networks:
      - backend

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    image: laravel-php:latest
    volumes:
      - ./:/var/www/app
    networks:
      - backend
